[game.et]
master_key = "woetm"
master_type = "WOETM"
server_key = "woets"
server_type = "WOETS"

[game.q3a]
master_key = "q3m"
master_type = "Q3M"
server_key = "q3s"
server_type = "Q3S"

[game.xonotic]
master_key = "xonoticm"
master_type = "XONOTICM"
server_key = "xonotics"
server_type = "XONOTICS"
