[game.csgo]
master_type = "STM"
server_type = "A2S"
server_gametype = "csgo"

[game.cstrike]
master_type = "STM"
server_type = "A2S"
server_gametype = "cstrike"

[game.dod]
master_type = "STM"
server_type = "A2S"
server_gametype = "dod"

[game.garrysmod]
master_type = "STM"
server_type = "A2S"
server_gametype = "garrysmod"

[game.gesource]
master_type = "STM"
server_type = "A2S"
server_gametype = "gesource"

[game.hl1mp]
master_type = "STM"
server_type = "A2S"
server_gametype = "hl1mp"

[game.hl2mp]
master_type = "STM"
server_type = "A2S"
server_gametype = "hl2mp"

[game.left4dead2]
master_type = "STM"
server_type = "A2S"
server_gametype = "left4dead2"

[game.portal2]
master_type = "STM"
server_type = "A2S"
server_gametype = "portal2"

[game.tf]
master_type = "STM"
server_type = "A2S"
server_gametype = "tf"

[game.alienarena]
master_type = "ALIENARENAM"
server_type = "ALIENARENAS"

[game.doom3]
master_type = "DM3M"
server_type = "DM3S"

[game.et]
master_type = "WOETM"
server_type = "WOETS"

[game.jediacademy]
master_type = "JK3M"
server_type = "JK3S"

[game.jedioutcast]
master_type = "JK2M"
server_type = "JK2S"

[game.openarena]
master_type = "OPENARENAM"
server_type = "OPENARENAS"

[game.q2]
master_type = "Q2M"
server_type = "Q2S"

[game.q3a]
master_type = "Q3M"
server_type = "Q3S"

[game.q4]
master_type = "Q4M"
server_type = "Q4S"

[game.qw]
master_type = "QWM"
server_type = "QWS"

[game.rtcw]
master_type = "RWM"
server_type = "RWS"

[game.openttd]
master_type = "OTTDM"
server_type = "OTTDS"

[game.stef1]
master_type = "EFM"
server_type = "EFS"

[game.turtlearena]
master_type = "TURTLEARENAM"
server_type = "TURTLEARENAS"

[game.unvanquished]
master_type = "UNVANQUISHEDM"
server_type = "UNVANQUISHEDS"

[game.urbanterror]
master_type = "IOURTM"
server_type = "IOURTS"

[game.warsow]
master_type = "WARSOWM"
server_type = "WARSOWS"

[game.wop]
master_type = "WOPM"
server_type = "WOPS"

[game.xonotic]
master_type = "XONOTICM"
server_type = "XONOTICS"
