[game.doom3]
master_key = "dm3m"
master_type = "DM3M"
server_key = "dm3s"
server_type = "DM3S"

[game.et]
master_key = "woetm"
master_type = "WOETM"
server_key = "woets"
server_type = "WOETS"

[game.openarena]
master_key = "openarenam"
master_type = "OPENARENAM"
server_key = "openarenas"
server_type = "OPENARENAS"

[game.q2]
master_key = "q2m"
master_type = "Q2M"
server_key = "q2s"
server_type = "Q2S"

[game.q3a]
master_key = "q3m"
master_type = "Q3M"
server_key = "q3s"
server_type = "Q3S"

[game.q4]
master_key = "q4m"
master_type = "Q4M"
server_key = "q4s"
server_type = "Q4S"

[game.qw]
master_key = "qwm"
master_type = "QWM"
server_key = "qws"
server_type = "QWS"

[game.rtcw]
master_key = "rwm"
master_type = "RWM"
server_key = "rws"
server_type = "RWS"

[game.openttd]
master_key = "ottdm"
master_type = "OTTDM"
server_key = "ottds"
server_type = "OTTDS"

[game.unvanquished]
master_key = "unvanquishedm"
master_type = "UNVANQUISHEDM"
server_key = "unvanquisheds"
server_type = "UNVANQUISHEDS"

[game.xonotic]
master_key = "xonoticm"
master_type = "XONOTICM"
server_key = "xonotics"
server_type = "XONOTICS"
