[rigsofrods]
path = "RoR"
master_uri = "http://api.rigsofrods.com/serverlist/"

[q2]
workdir = ""
path = "quake2"
master_uri = "netdome.biz:27900"

[q3a]
workdir = ""
path = "quake3"
master_uri = "master3.idsoftware.com:27950, master.quake3arena.com:27950, master.ioquake3.org:27950, dpmaster.deathmask.net:27950, master.maverickservers.com:27950"

[q4]
workdir = ""
path = "quake4"
master_uri = "q4master.idsoftware.com:27650"

[qw]
workdir = ""
path = "qwcl"
master_uri = "qwmaster.ocrana.de:27000"

[et]
workdir = ""
path = "et"
master_uri = "etmaster.idsoftware.com:27950"

[unvanquished]
workdir = ""
path = "unvanquished"
master_uri = "unvanquished.net:27950"

[xonotic]
workdir = ""
path = "xonotic-sdl"
master_uri = "ghdigital.com:27950, dpmaster.deathmask.net:27950, dpmaster.tchr.no:27950"
