sudo: false
addons:
  apt:
    packages:
    - libgtk-3-0
    - python3-gi
    - qstat
language: python
python:
  - "3.4"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m tests.tests
