[[games]]
id = "rigsofrods"
workdir = ""
path = ""
master_uri = "http://api.rigsofrods.com/serverlist/"

[[games]]
id = "q3a"
workdir = ""
path = ""
master_uri = ""

[common]
nickname = ""
server-pass = ""
server-host = "127.0.0.1"
pinging-enable = false
selected-game = ""
