[rigsofrods]
name = "Rigs of Rods"
backend = "rigsofrods"
launch_pattern = "rigsofrods"
settings = ["path", "master_uri"]

[csgo]
name = "Counter-Strike: Global Offensive"
backend = "qstat"
launch_pattern = "hl2"
steam_app_id = "730"
settings = ["path", "workdir", "master_uri", "steam_launch", "steam_path"]

[cstrike]
name = "Counter-Strike: Source"
backend = "qstat"
launch_pattern = "hl2"
steam_app_id = "240"
settings = ["path", "workdir", "master_uri", "steam_launch", "steam_path"]

[gesource]
name = "GoldenEye: Source"
backend = "qstat"
launch_pattern = "hl2"
settings = ["path", "master_uri"]

[hl1mp]
name = "Half-Life Deathmatch: Source"
backend = "qstat"
launch_pattern = "hl2"
steam_app_id = "360"
settings = ["path", "workdir", "master_uri", "steam_launch", "steam_path"]

[hl2mp]
name = "Half-Life 2: Deathmatch"
backend = "qstat"
launch_pattern = "hl2"
steam_app_id = "320"
settings = ["path", "workdir", "master_uri", "steam_launch", "steam_path"]

[portal2]
name = "Portal 2"
backend = "qstat"
launch_pattern = "hl2"
steam_app_id = "620"
settings = ["path", "workdir", "master_uri", "steam_launch", "steam_path"]

[alienarena]
name = "Alien Arena"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[doom3]
name = "Doom 3"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[jediacademy]
name = "Star Wars Jedi Knight II: Jedi Academy"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[jedioutcast]
name = "Star Wars Jedi Knight II: Jedi Outcast"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[q2]
name = "Quake II"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[q3a]
name = "Quake III Arena"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[q4]
name = "Quake 4"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[qw]
name = "QuakeWorld"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[rtcw]
name = "Return to Castle Wolfenstein"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[et]
name = "Wolfenstein: Enemy Territory"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[openarena]
name = "OpenArena"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[openttd]
name = "OpenTTD"
backend = "qstat"
launch_pattern = "openttd"
settings = ["path", "master_uri"]

[stef1]
name = "Star Trek: Voyager - Elite Force"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[turtlearena]
name = "Turtle Arena"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[unvanquished]
name = "Unvanquished"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[urbanterror]
name = "Urban Terror"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[warsow]
name = "Warsow"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[wop]
name = "World of Padman"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[xonotic]
name = "Xonotic"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]
