[rigsofrods]
name = "Rigs of Rods"
backend = "rigsofrods"
settings = ["path", "master_uri"]

[q3a]
name = "Quake III Arena"
backend = "qstat"
settings = ["path", "workdir", "master_uri"]

[et]
name = "Wolfenstein: Enemy Territory"
backend = "qstat"
settings = ["path", "workdir", "master_uri"]

[unvanquished]
name = "Unvanquished"
backend = "qstat"
settings = ["path", "workdir", "master_uri"]

[xonotic]
name = "Xonotic"
backend = "qstat"
settings = ["path", "workdir", "master_uri"]
