[rigsofrods]
name = "Rigs of Rods"
backend = "rigsofrods"
launch_pattern = "rigsofrods"
settings = ["path", "master_uri"]

[doom3]
name = "Doom 3"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[q2]
name = "Quake II"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[q3a]
name = "Quake III Arena"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[q4]
name = "Quake 4"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[qw]
name = "QuakeWorld"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[rtcw]
name = "Return to Castle Wolfenstein"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[et]
name = "Wolfenstein: Enemy Territory"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[openarena]
name = "OpenArena"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[openttd]
name = "OpenTTD"
backend = "qstat"
launch_pattern = "openttd"
settings = ["path", "master_uri"]

[stef1]
name = "Star Trek: Voyager - Elite Force"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[turtlearena]
name = "Turtle Arena"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[unvanquished]
name = "Unvanquished"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[urbanterror]
name = "Urban Terror"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[wop]
name = "World of Padman"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]

[xonotic]
name = "Xonotic"
backend = "qstat"
launch_pattern = "quake"
settings = ["path", "workdir", "master_uri"]
