[rigsofrods]
name = "Rigs of Rods"
backend = "rigsofrods"
settings = ["path"]

[q3a]
name = "Quake III Arena"
backend = "qstat"
settings = ["path", "workdir", "master_uri"]

[et]
name = "Wolfenstein: Enemy Territory"
backend = "qstat"
settings = ["path", "workdir", "master_uri"]
