[common.selected-game]
gtk_widget_name="Game_ComboBox"

[common.nickname]
gtk_widget_name = "Nickname_Entry"

[common.server-host]
gtk_widget_name="ServerHost_Entry"

[common.server-pass]
gtk_widget_name="ServerPass_Entry"
