[[games]]
id = "rigsofrods"
workdir = ""
path = ""

[[games]]
id = "q3a"
workdir = ""
path = ""

[common]
nickname = ""
server-pass = ""
server-host = "127.0.0.1"
pinging-enable = false
selected-game = ""
