
[games]

[[games.entry]]
id = "rigsofrods"
workdir = ""
path = ""

[[games.entry]]
id = "q3a"
workdir = ""
path = ""

[general]
nickname = ""
server-pass = ""
server-host = "127.0.0.1"
pinging-enable = false
selected-game = ""
