[path]
name = "Game path"
description = "Path to the game"
gtk_type = "Entry with Label"

[workdir]
name = "Working directory"
description = "Working directory of the game"
gtk_type = "Entry with Label"

[master_uri]
name = "Master URI list"
description = "List of master servers to query"
gtk_type = "Entry with Label"
